#!/bin/sh
#chkconfig: 2345 65 35
#description: start or stop rocketmq using chkconfig
 
dir=/usr/local/rocketmq
export JAVA_HOME=/usr/local/jdk8
 
start() {
	if [ -f ${dir}/bin/mqbroker ]; then
		echo "starting rocketmq broker.."
		cd ${dir}/bin
		
		nohup sh mqbroker -n 192.168.1.110:9876 >/usr/local/rocketmq/logs/broker.log 2>&1 &

		echo "start sucess"

	fi
}
 
stop() {
	if [ -f ${dir}/bin/mqshutdown ]; then
		echo "stopping rocketmq broker.."
		cd ${dir}/bin
		./mqshutdown broker
		echo "stop success"

	fi
}
 
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		echo "restarting rocketmq broker.."
		$0 stop
		sleep 1
		$0 start
		;;
	*)
		echo $"Usage:$0 {start|stop|restart}"
		exit 1
		;;
esac
exit 0